#pragma once
#ifndef MUIRECTANGLEH
#define MUIRECTANGLEH
#include "../mui/mui.h"

#include "bytes/bytes.h"
#include "c_stringfn/include/stringfn.h"
#include "libtmt/tmt.h"
#include "ms/ms.h"

#include <assert.h>
#include <assert.h>
#include <ApplicationServices/ApplicationServices.h>
#include <Carbon/Carbon.h>
#include <fnmatch.h>
#include <libproc.h>
#include <mach/mach_time.h>
#include <stdbool.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/proc_info.h>
#include <sys/sysctl.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#define COLOR_NAMES_DB_PATH    "etc/colornames.bestof.sqlite"
#include "../mui-render/mui-render-options.h"
#include "../mui-render/mui-render.h"
#include "../mui/mui.h"
#include "c_deps/submodules/c_colors/db/db.h"
#include "c_deps/submodules/c_darwin/active-app/active-app.h"
#include "c_deps/submodules/c_string_buffer/include/stringbuffer.h"
#include "c_deps/submodules/c_stringfn/include/stringfn.h"
#include "c_deps/submodules/parson/parson.h"

#include "SDL2/SDL_image.h"
#include "timestamp/timestamp.h"

#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_mutex.h>
#include <SDL2/SDL_thread.h>
#ifdef WINDOW_WIDTH
#undef WINDOW_WIDTH
#endif

#define WINDOW_WIDTH                650
#define          BUTTONS_PER_ROW    5
#define          BUTTON_PADDING     5
#define          BUTTON_SIZE        125
#define          BUTTON_ICON        0
#define          BUTTON_HEIGHT      25
#define CFG_TITLE                   "Rectangle Manager"
#define CFG_X_OFFSET                50
#define CFG_Y_OFFSET                50
#define CFG_WIDTH                   (BUTTON_SIZE * BUTTONS_PER_ROW)
#define CFG_OPTIONS         \
  SDL_WINDOW_ALLOW_HIGHDPI  \
  | SDL_WINDOW_OPENGL       \
  | SDL_WINDOW_POPUP_MENU   \
  | SDL_WINDOW_BORDERLESS   \
  | SDL_WINDOW_SKIP_TASKBAR \
  | SDL_WINDOW_ALWAYS_ON_TOP
#define BASIC_WINDOW_TITLE          "Windows"
#define BASIC_WINDOW_HEIGHT         300
#define BASIC_WINDOW_OPTIONS        MU_OPT_NODRAG | MU_OPT_NOCLOSE
#define RETAIN_INITIAL_FOCUS        true
struct tmt_exec_t {
  char                *input;
  size_t              rows, cols, callbacks_qty;
  int                 cursor_pos_x, cursor_pos_y;
  char                *cursor_state;
  struct Vector       *output_lines, *plaintext_lines;
  struct StringBuffer *output_buffer, *plaintext_buffer;
  long unsigned       started_ms, dur_ms;
};
int mui_rectangle();
int tmt_exec(struct tmt_exec_t *);
static char COLOR_REPORT_B64[] = "U3lzdGVtIGNvbG9yczoNChtbNDg7NTswbTo6G1s0ODs1OzFtOjobWzQ4OzU7Mm06OhtbNDg7NTszbTo6G1s0ODs1OzRtOjobWzQ4OzU7NW06OhtbNDg7NTs2bTo6G1s0ODs1OzdtOjobWzBtDQobWzQ4OzU7OG06OhtbNDg7NTs5bTo6G1s0ODs1OzEwbTo6G1s0ODs1OzExbTo6G1s0ODs1OzEybTo6G1s0ODs1OzEzbTo6G1s0ODs1OzE0bTo6G1s0ODs1OzE1bTo6G1swbQ0K";
#define COLOR_REPORT_B64    "IBtbbRtbNDBtICDigKLigKLigKIgIBtbMG0gG1ttG1s0MW0gIOKAouKAouKAoiAgG1swbSAbW20bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbbRtbNDNtICDigKLigKLigKIgIBtbMG0gG1ttG1s0NG0gIOKAouKAouKAoiAgG1swbSAbW20bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbbRtbNDZtICDigKLigKLigKIgIBtbMG0gG1ttG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMW0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMW0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szMG0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzBtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzMwbRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szMG0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzBtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzMwbRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szMG0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzBtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszMG0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMG0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szMW0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzFtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzMxbRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szMW0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzFtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzMxbRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szMW0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzFtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszMW0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMW0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szMm0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzJtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzMybRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szMm0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzJtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzMybRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szMm0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzJtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszMm0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszMm0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szM20bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzNtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzMzbRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szM20bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzNtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzMzbRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szM20bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzNtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszM20bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszM20bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szNG0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzRtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzM0bRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szNG0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzRtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzM0bRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szNG0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzRtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszNG0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNG0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szNW0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzVtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzM1bRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szNW0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzVtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzM1bRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szNW0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzVtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszNW0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNW0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szNm0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzZtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzM2bRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szNm0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzZtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzM2bRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szNm0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzZtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszNm0bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszNm0bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQogG1szN20bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMzdtG1s0MW0gIOKAouKAouKAoiAgG1swbSAbWzM3bRtbNDJtICDigKLigKLigKIgIBtbMG0gG1szN20bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMzdtG1s0NG0gIOKAouKAouKAoiAgG1swbSAbWzM3bRtbNDVtICDigKLigKLigKIgIBtbMG0gG1szN20bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMzdtG1s0N20gIOKAouKAouKAoiAgG1swbQ0KIBtbMTszN20bWzQwbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQxbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQybSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQzbSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQ0bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQ1bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQ2bSAg4oCi4oCi4oCiICAbWzBtIBtbMTszN20bWzQ3bSAg4oCi4oCi4oCiICAbWzBtDQoNCg=="

#endif
